---
name: nginx

director_uuid: 84aa92b0-0756-428c-a91e-7db798d20026

releases:
- name: nginx
  version: latest
- name: nginx-multiple-ssl-addon
  version: latest

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: nginx-ubuntu
  instances: 1
  vm_type: default
  stemcell: ubuntu
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: tls-config
    release: nginx-multiple-ssl-addon
    properties:
      ssl:
        cert_folder: /var/vcap/jobs/tls-config/certs/
        nginx_conf_folder: /var/vcap/jobs/tls-config/vhosts/
        certs:
        - name: dta_cornmbank_com
          conf: |
            server {
                server_name dta.cornmbank.com;
                # SSL configuration
                listen *:443 ssl;
                ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
                ssl_prefer_server_ciphers on;
                ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
                ssl_ecdh_curve secp384r1;
                ssl_session_cache shared:SSL:10m;
                ssl_session_tickets off;
                ssl_stapling on;
                ssl_stapling_verify on;
                add_header X-Frame-Options DENY;
                add_header X-Content-Type-Options nosniff;
                # disable HSTS header for now
                # add_header Strict-Transport-Security "max-age=63072000;
                ssl_certificate /var/vcap/jobs/tls-config/certs/dta_cornmbank_com.crt;
                ssl_certificate_key /var/vcap/jobs/tls-config/certs/dta_cornmbank_com.key;
                location / {
                  proxy_pass http://internal-z-cld-gov-au-internal-apps-elb-828227269.ap-southeast-2.elb.amazonaws.com;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-for $remote_addr;
                  proxy_set_header Host $http_host;
                }
            }
          ## Ideally this is what we want to use so we can store all keys and certs in credhub.
          ## Unfortunately i am having some issue in my local build at the moment.
          fullchain: ((dta_cornmbank_com.ca))
          private_key: ((dta_cornmbank_com.private_key))
          certificate: ((dta_cornmbank_com.certificate))

  - name: nginx
    release: nginx
    properties:
      nginx_conf: |
        worker_processes  1;
        error_log /var/vcap/sys/log/nginx/error.log   info;
        #pid        logs/nginx.pid; # PIDFILE is configured via monit's ctl
        events {
          worker_connections  1024;
        }
        http {
          include /var/vcap/packages/nginx/conf/mime.types;
          default_type  application/octet-stream;
          sendfile        on;
          ssi on;
          keepalive_timeout  65;
          server_names_hash_bucket_size 64;
          server {
              listen *:80;
              server_name _;
              return 301 https://$host$request_uri;
          }
          # For better security we may wanna generate dhparam later?
          # ssl_dhparam /var/vcap/jobs/nginx/conf/dhparam.pem;
          # Include all vhosts files from our addon-release folder
          include /var/vcap/jobs/tls-config/vhosts/*.conf;
        }

## This is broken for some reason at the moment with credhub. Further investigation need to be done.
variables:
- name: dta_cornmbank_com
  type: certificate

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
